// <auto-generated />
using DataAccess.DataBase;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.DataBase.Migrations
{
	[DbContext(typeof(CvDbContext))]
	partial class CvDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.2")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("Entities.Customer", b =>
				{
					b.Property<int>("CustomerId")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

					b.Property<string>("CompanyName")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Email")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Phone")
						.HasColumnType("nvarchar(450)");

					b.HasKey("CustomerId");

					b.HasIndex("CompanyName");

					b.HasIndex("Email");

					b.HasIndex("Name");

					b.HasIndex("Phone");

					b.ToTable("Customers", (string)null);
				});
#pragma warning restore 612, 618
		}
	}
}
